"""empty message

Revision ID: 3fd69885df22
Revises: 5b5e195680c5
Create Date: 2021-08-20 21:55:40.779276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd69885df22'
down_revision = '5b5e195680c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'available')
    # ### end Alembic commands ###
