"""empty message

Revision ID: 5b5e195680c5
Revises: cb77008957f4
Create Date: 2021-08-16 22:19:27.409353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5e195680c5'
down_revision = 'cb77008957f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password_hash')
    # ### end Alembic commands ###
