"""empty message

Revision ID: 635570ce9fe6
Revises: 7a1b8fb13c05
Create Date: 2021-08-22 19:18:12.623565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635570ce9fe6'
down_revision = '7a1b8fb13c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_project',
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['timer_id'], ['timer.id'], ),
    sa.PrimaryKeyConstraint('timer_id', 'project_id')
    )
    op.drop_table('timers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('timer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='timers_project_id_fkey'),
    sa.ForeignKeyConstraint(['timer_id'], ['timer.id'], name='timers_timer_id_fkey')
    )
    op.drop_table('timer_project')
    # ### end Alembic commands ###
