"""empty message

Revision ID: 7a1b8fb13c05
Revises: 0c36582d966b
Create Date: 2021-08-22 19:13:18.861637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1b8fb13c05'
down_revision = '0c36582d966b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_tag',
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['timer_id'], ['timer.id'], ),
    sa.PrimaryKeyConstraint('timer_id', 'tag_id')
    )
    op.add_column('timers', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('timers_tag_id_fkey', 'timers', type_='foreignkey')
    op.create_foreign_key(None, 'timers', 'project', ['project_id'], ['id'])
    op.drop_column('timers', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timers', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timers', type_='foreignkey')
    op.create_foreign_key('timers_tag_id_fkey', 'timers', 'tag', ['tag_id'], ['id'])
    op.drop_column('timers', 'project_id')
    op.drop_table('timer_tag')
    # ### end Alembic commands ###
