"""empty message

Revision ID: cb77008957f4
Revises: 54b258ffb2c1
Create Date: 2021-08-16 22:18:42.597483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb77008957f4'
down_revision = '54b258ffb2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
