"""empty message

Revision ID: fbbe9edd522d
Revises: 3fd69885df22
Create Date: 2021-08-22 07:56:51.856499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbe9edd522d'
down_revision = '3fd69885df22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available')
    op.drop_column('tag', 'available')
    # ### end Alembic commands ###
